### PR TITLE
Prepare for 1.1.1 release

### PR DESCRIPTION
**Pull request by MoLi7**
Added a few final touches including:
- Update useeior tag to `SEF_v1.1.1` and version to `1.0.2`
- Add `GenerateEmissionFactorsDataset.Rmd` to create results in Excel only using `CalculateEF.Rmd` which will be used as core script for future developemt
- Add/Modify functions to improve user experience and/or ensure model specs are correctly created.

### CODE REVIEW

**Comment by MoLi7** [comment]
I cleaned up the old metadata and added them in`GenerateEmissionFactorsDataset.Rmd`. Knitting it will return a `_v1.1.1.xlsx` file.

**Comment by MoLi7** [comment]
I also updated the link to useeior in the release note. Once this PR is merged, we can publish the release.

**Comment by WesIngwersen** [comment]
Please remove the GenerateEmissionFactorsDataset.Rmd. We can include it as a supporting file to the dataset release.

**Review by WesIngwersen — CHANGES_REQUESTED** [review]
The info about package install seems to be supressed, except the prompt, so the user won't know what numbers to enter or how to proceed

image

**Comment by WesIngwersen** [comment]
I'm getting an error with cli here:
https://github.com/USEPA/supply-chain-factors/blob/6549ca0d0b5ca05d1f98b94d2fdd8ab494fe6ad1/R/utils.R#L19
`Error in if (node$tag == "span") { : argument is of length zero`

**Comment by MoLi7** [comment]
Ready for merge? @WesIngwersen

**Pull request merged**
